Add a timestamp to the bottom right corner of the map
jonatkins/ingress-intel-total-conversion pull request #1192
Opened 2017-03-01 00:39 UTC by pleasantone

Does what it says, very useful for screenshots.

2017-04-11 19:28 UTC, dingram requested changes

2017-04-11 19:28 UTC, dingram commented on plugins/map-timestamp.user.js
> +  $('#timestamp').html(html);
This could be `.text()` instead, as there is no HTML. Best to be safe :smiley:

2017-04-11 22:25 UTC, pleasantone commented
Requested changes made.

2017-04-11 22:30 UTC, pleasantone commented on plugins/map-timestamp.user.js
> +  $('#timestamp').html(html);
totally agree, changes made

2017-05-30 19:04 UTC, pleasantone commented
@dingram poke

2022-12-28 23:10 UTC, closed without merging